/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author W1784229 Ibraheem Ahmed, W1758597 Rabiul Alam
 */
public class A1 extends javax.swing.JPanel {

    /**
     * Creates new form A1
     */
    
    private String conv_A= "";
    private String conv_B = "";
    private String grammar_structure = "";
    private String key_vocab = "";
             

    public A1() {
        initComponents();
        
    
    }
    public void a1() {
        
    }
    public void addEventMenu(ActionListener event) {
        back.addActionListener(event);
    }
    public void addEventDialogue(ActionListener event) {
        Submit.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelA1Label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        A1_Cmb = new javax.swing.JComboBox<>();
        A1_Sub_Cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Submit = new swing.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LevelA1Label.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        LevelA1Label.setForeground(new java.awt.Color(69, 68, 68));
        LevelA1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelA1Label.setText("Level A1");
        LevelA1Label.setMaximumSize(new java.awt.Dimension(193, 59));
        LevelA1Label.setMinimumSize(new java.awt.Dimension(193, 59));

        back.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 153, 153));
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Context:");

        A1_Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Introductions", "Ordering food and drink", "Going shopping and asking for prices", "Exchanging personal information", "Making appointments", "Basic employment issues", "Socialising in the country", "Asking and giving directions", "Mkaing invitations", "University life", "Cross-cultural experiences", " " }));
        A1_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_CmbActionPerformed(evt);
            }
        });

        A1_Sub_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_Sub_CmbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Sub-Context:");

        Submit.setBackground(new java.awt.Color(255, 153, 153));
        Submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Submit.setForeground(new java.awt.Color(40, 40, 40));
        Submit.setText("Submit");
        Submit.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        Submit.setMaximumSize(new java.awt.Dimension(81, 27));
        Submit.setMinimumSize(new java.awt.Dimension(81, 27));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(LevelA1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(A1_Cmb, 0, 0, Short.MAX_VALUE)
                    .addComponent(A1_Sub_Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LevelA1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(A1_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(A1_Sub_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO
    }//GEN-LAST:event_backActionPerformed

    private void A1_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_CmbActionPerformed
        if(A1_Cmb.getSelectedItem().equals("Ordering food and drink")){
            A1_Sub_Cmb.removeAllItems();
            A1_Sub_Cmb.addItem("Takeaway");
            A1_Sub_Cmb.addItem("Coffee Order");
            A1_Sub_Cmb.addItem("Water for table");
            A1_Sub_Cmb.addItem("Reservation");
            A1_Sub_Cmb.addItem("Cocktails by card payment");
        }
        else
            if(A1_Cmb.getSelectedItem().equals("Exchanging personal information")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Social Media");
                A1_Sub_Cmb.addItem("Neighbours parcel");
                A1_Sub_Cmb.addItem("Description of town");
            }
        
        else
            if(A1_Cmb.getSelectedItem().equals("Going shopping and asking for prices")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Payment");
                A1_Sub_Cmb.addItem("Refund");
            }
        
        else
                if(A1_Cmb.getSelectedItem().equals("Making appointments")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Booking");
                A1_Sub_Cmb.addItem("Spelling your name");
            }
        
        else
                if(A1_Cmb.getSelectedItem().equals("Introductions")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Repeat name");
            }
        
         else
                if(A1_Cmb.getSelectedItem().equals("Basic employment issues")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Cover");
                A1_Sub_Cmb.addItem("Interview");
            }
        
         else
                if(A1_Cmb.getSelectedItem().equals("Socialising in the country")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.setSelectedItem(null);
                A1_Sub_Cmb.addItem("Interview arrangements"); 
            }
        
        else
                if(A1_Cmb.getSelectedItem().equals("Asking and giving directions")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.addItem("Delivery Driver");
            }
               
        else
                if(A1_Cmb.getSelectedItem().equals("Making invitations")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.setSelectedItem(null);
                A1_Sub_Cmb.addItem("Disneyland");
                A1_Sub_Cmb.addItem("Help ith childs birthday party");
            }
        
                  
        else
                if(A1_Cmb.getSelectedItem().equals("University life")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.setSelectedItem(null);
                A1_Sub_Cmb.addItem("Study in cafe");
            }
        
        
                else
                if(A1_Cmb.getSelectedItem().equals("Cross-cultural experiences")){
                A1_Sub_Cmb.removeAllItems();
                A1_Sub_Cmb.setSelectedItem(null);
                A1_Sub_Cmb.addItem("International Food");
            }
        
    }//GEN-LAST:event_A1_CmbActionPerformed
    
    
    public void select(){
         Main main = new Main();
        try{
        Connection con = connectDB.getConnection();
        
        String context = A1_Cmb.getSelectedItem().toString();
        String sub_context = A1_Sub_Cmb.getSelectedItem().toString();
        
        
        String sql = "Select Conv_A,Conv_B,Grammar_Structure,Key_Vocab from A1 where Context='" + context + "'" + "and sub_context='" + sub_context + "'";
            System.out.println(sql);
       
        
        PreparedStatement pst = con.prepareStatement(sql);
        
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){
            conv_A = rs.getString("Conv_A");
            conv_B = rs.getString("Conv_B");
            key_vocab = rs.getString("Key_Vocab");
            grammar_structure = rs.getString("Grammar_Structure");
            
            main.setDialogueText(conv_A,conv_B,key_vocab,grammar_structure);
        }
        rs.close();
        con.close();
        }catch(Exception e){
            System.out.println("problem with SQLite close connection");
        }
        
        main.setVisible(true);
        main.showDialogue();
      
    }
   
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        select();
    }//GEN-LAST:event_SubmitActionPerformed

    private void A1_Sub_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_Sub_CmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1_Sub_CmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A1_Cmb;
    private javax.swing.JComboBox<String> A1_Sub_Cmb;
    private javax.swing.JLabel LevelA1Label;
    private swing.MyButton Submit;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
