/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author W1784229 Ibraheem Ahmed, W1758597 Rabiul Alam
 */
public class A2 extends javax.swing.JPanel {

    
    /**
     * Creates new form A2
     */
    
    private String conv_A = "";
    private String conv_B = "";
    private String grammar_structure = "";
    private String key_vocab = "";
     
     
    public A2() {
        initComponents();
    }
    public void a2() {
        
    }
    public void addEventMenu(ActionListener event) {
        back.addActionListener(event);
    }
    public void addEventDialogue(ActionListener event) {
        Submit.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        LevelA2Label = new javax.swing.JLabel();
        A2_Cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        A2_Sub_Cmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Submit = new swing.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        back.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 153, 153));
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        LevelA2Label.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        LevelA2Label.setForeground(new java.awt.Color(69, 68, 68));
        LevelA2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelA2Label.setText("Level A2");
        LevelA2Label.setMaximumSize(new java.awt.Dimension(193, 59));
        LevelA2Label.setMinimumSize(new java.awt.Dimension(193, 59));

        A2_Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Introductions", "Making appointments", "Asking and giving directions", "Making invitations", "Ordering food and drink", "Going shopping and asking for prices", "Health matters", "Socialising", "Socialising in the country", "Making travel arrangements", "Exchanging personal information", "Cross-cultural experieneces", "Weather", "Weather and weather conditions" }));
        A2_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_CmbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Context:");

        A2_Sub_Cmb.setToolTipText("");
        A2_Sub_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_Sub_CmbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Sub-Context:");

        Submit.setBackground(new java.awt.Color(255, 153, 153));
        Submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Submit.setForeground(new java.awt.Color(40, 40, 40));
        Submit.setText("Submit");
        Submit.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        Submit.setMaximumSize(new java.awt.Dimension(81, 27));
        Submit.setMinimumSize(new java.awt.Dimension(81, 27));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(LevelA2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(A2_Cmb, 0, 0, Short.MAX_VALUE)
                    .addComponent(A2_Sub_Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LevelA2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(A2_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(A2_Sub_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO
    }//GEN-LAST:event_backActionPerformed

    private void A2_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_CmbActionPerformed
        if(A2_Cmb.getSelectedItem().equals("Introductions")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("1st day in job");
            A2_Sub_Cmb.addItem("Job offer");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making appointments")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Dentist");
            A2_Sub_Cmb.addItem("Doctor");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Asking and giving directions")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Delivery Driver");
            A2_Sub_Cmb.addItem("Hospital visit");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making invitations")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Charity");
            A2_Sub_Cmb.addItem("Lunch");
            A2_Sub_Cmb.addItem("Children at wedding");
            A2_Sub_Cmb.addItem("Wedding RSVP");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Ordering food and drink")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Vegan pizza");
            A2_Sub_Cmb.addItem("Reservation");
            A2_Sub_Cmb.addItem("Delayed drinks order");
            A2_Sub_Cmb.addItem("QR Code");
            A2_Sub_Cmb.addItem("Cocktails 1");
            A2_Sub_Cmb.addItem("Cocktails 2");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Going shopping and asking for prices")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Payment");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Health matters")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Sick relative");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Socialising in the country")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Family size");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making travel arrangements")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Expired ticket");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Exchanging personal information")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Age restricted");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Cross-cultural experiences")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Omelette");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Weather and weather conditions")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Clothing for weather");
        }
        
         else
        if(A2_Cmb.getSelectedItem().equals("Health")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Visiting patient");
        }
        
          else
        if(A2_Cmb.getSelectedItem().equals("Socialising")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.addItem("Succulent");
        }
        
    }//GEN-LAST:event_A2_CmbActionPerformed
          
    public void select(){
         Main main = new Main();
        try{
        Connection con = connectDB.getConnection();
        
        String context = A2_Cmb.getSelectedItem().toString();
        String sub_context = A2_Sub_Cmb.getSelectedItem().toString();
        
        
        String sql = "Select Conv_A,Conv_B,Grammar_Structure,Key_Vocab from A2 where Context='" + context + "'" + "and sub_context='" + sub_context + "'";
        System.out.println(sql);
       
        
        PreparedStatement pst = con.prepareStatement(sql);
        
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){
            conv_A = rs.getString("Conv_A");
            conv_B = rs.getString("Conv_B");
            key_vocab = rs.getString("Key_Vocab");
            grammar_structure = rs.getString("Grammar_Structure");
            
            main.setDialogueText(conv_A,conv_B,key_vocab,grammar_structure);
        }
        rs.close();
        con.close();
        }catch(Exception e){
            System.out.println("problem with SQLite close connection.");
        }
        
        main.setVisible(true);
        main.showDialogue();
        
        
        
    }
    
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        
        select();
    }//GEN-LAST:event_SubmitActionPerformed

    private void A2_Sub_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_Sub_CmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2_Sub_CmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A2_Cmb;
    private javax.swing.JComboBox<String> A2_Sub_Cmb;
    private javax.swing.JLabel LevelA2Label;
    private swing.MyButton Submit;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
