/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author W1784229 Ibraheem Ahmed, W1758597 Rabiul Alam
 */
public class B2 extends javax.swing.JPanel {

    /**
     * Creates new form B2
     */
    private String conv_A = "";
    private String conv_B = "";
    private String grammar_structure = "";
    private String key_vocab = "";
 
    public B2() {
        initComponents();
    }
    public void b2() {
       
    }
    public void addEventMenu(ActionListener event) {
        back.addActionListener(event);
    }
    public void addEventDialogue(ActionListener event) {
        Submit.addActionListener(event);
    }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelB2Label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        B2_Cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        B2_Sub_Cmb = new javax.swing.JComboBox<>();
        Submit = new swing.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LevelB2Label.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        LevelB2Label.setForeground(new java.awt.Color(69, 68, 68));
        LevelB2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelB2Label.setText("Level B2");
        LevelB2Label.setMaximumSize(new java.awt.Dimension(193, 59));
        LevelB2Label.setMinimumSize(new java.awt.Dimension(193, 59));

        back.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 153, 153));
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Sub-Context:");

        B2_Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Going shopping and asking for prices", "Work life", "Making travel arrangements", "Socialising in the country" }));
        B2_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_CmbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Context:");

        B2_Sub_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_Sub_CmbActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(255, 153, 153));
        Submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Submit.setForeground(new java.awt.Color(40, 40, 40));
        Submit.setText("Submit");
        Submit.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        Submit.setMaximumSize(new java.awt.Dimension(81, 27));
        Submit.setMinimumSize(new java.awt.Dimension(81, 27));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(B2_Cmb, 0, 0, Short.MAX_VALUE)
                    .addComponent(LevelB2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(B2_Sub_Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LevelB2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(B2_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(B2_Sub_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO
    }//GEN-LAST:event_backActionPerformed

    private void B2_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_CmbActionPerformed
        if(B2_Cmb.getSelectedItem().equals("Going shopping and asking for prices")){
            B2_Sub_Cmb.removeAllItems();
            B2_Sub_Cmb.addItem("Phone purchase");
        }
        else
        if(B2_Cmb.getSelectedItem().equals("Work life")){
            B2_Sub_Cmb.removeAllItems();
            B2_Sub_Cmb.addItem("Meet for drinks");
        }
        else
        if(B2_Cmb.getSelectedItem().equals("Making travel arrangements")){
            B2_Sub_Cmb.removeAllItems();
            B2_Sub_Cmb.setSelectedItem(null);
            B2_Sub_Cmb.addItem("Disneyland");
        }
        else
        if(B2_Cmb.getSelectedItem().equals("Socialising in the country")){
            B2_Sub_Cmb.removeAllItems();
            B2_Sub_Cmb.addItem("No show date");
        }
    }//GEN-LAST:event_B2_CmbActionPerformed

    public void select(){
         Main main = new Main();
        try{
        Connection con = connectDB.getConnection();
        
        String context = B2_Cmb.getSelectedItem().toString();
        String sub_context = B2_Sub_Cmb.getSelectedItem().toString();
        
        
        String sql = "Select Conv_A,Conv_B,Grammar_Structure,Key_Vocab from B2 where Context='" + context + "'" + "and sub_context='" + sub_context + "'";
            System.out.println(sql);
       
        
        PreparedStatement pst = con.prepareStatement(sql);
        
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){
            conv_A = rs.getString("Conv_A");
            conv_B = rs.getString("Conv_B");
            key_vocab = rs.getString("Key_Vocab");
            grammar_structure = rs.getString("Grammar_Structure");
            
            main.setDialogueText(conv_A,conv_B,key_vocab,grammar_structure);
        }
        rs.close();
        con.close();
        }catch(Exception e){
              System.out.println("problem with SQLite close connection.");
        }
        
        main.setVisible(true);
        main.showDialogue();
        
        
        
    }
    
    private void B2_Sub_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_Sub_CmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2_Sub_CmbActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    // TODO add your handling code here:
    
    select();
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> B2_Cmb;
    private javax.swing.JComboBox<String> B2_Sub_Cmb;
    private javax.swing.JLabel LevelB2Label;
    public swing.MyButton Submit;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
