/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionListener;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author W1771719 Seyed Avin Moosavi Shirazi, W1758597 Alam Rabiul
 */
public class Dialogue extends javax.swing.JPanel {

    /**
     * Creates new form Translator
     */
    public Dialogue() {
        initComponents();        
    }
    public void dialogue() {   
    }
    public void addEventMenu(ActionListener event) {
        back.addActionListener(event);
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelB2Label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        StructureLabel = new javax.swing.JLabel();
        StructureOutput = new javax.swing.JTextField();
        VocabLabel = new javax.swing.JLabel();
        KeyVocabOutput = new javax.swing.JScrollPane();
        VocabOutput = new javax.swing.JTextArea();
        PersonALabel = new javax.swing.JLabel();
        PersonALabel1 = new javax.swing.JLabel();
        KeyVocabOutput1 = new javax.swing.JScrollPane();
        PersonBOutput = new javax.swing.JTextArea();
        KeyVocabOutput2 = new javax.swing.JScrollPane();
        PersonAOutput = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        LevelB2Label.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        LevelB2Label.setForeground(new java.awt.Color(69, 68, 68));
        LevelB2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LevelB2Label.setText("Dialogue");
        LevelB2Label.setMaximumSize(new java.awt.Dimension(193, 59));
        LevelB2Label.setMinimumSize(new java.awt.Dimension(193, 59));

        back.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 153, 153));
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        StructureLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        StructureLabel.setText("Grammar/Structure :");

        StructureOutput.setEditable(false);
        StructureOutput.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        StructureOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StructureOutputActionPerformed(evt);
            }
        });

        VocabLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        VocabLabel.setText("Key Vocabulary :");

        VocabOutput.setEditable(false);
        VocabOutput.setColumns(20);
        VocabOutput.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        VocabOutput.setRows(5);
        KeyVocabOutput.setViewportView(VocabOutput);

        PersonALabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        PersonALabel.setText("Person A :");

        PersonALabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        PersonALabel1.setText("Person B :");

        PersonBOutput.setEditable(false);
        PersonBOutput.setColumns(20);
        PersonBOutput.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        PersonBOutput.setRows(5);
        KeyVocabOutput1.setViewportView(PersonBOutput);

        PersonAOutput.setEditable(false);
        PersonAOutput.setColumns(20);
        PersonAOutput.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        PersonAOutput.setRows(5);
        KeyVocabOutput2.setViewportView(PersonAOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KeyVocabOutput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KeyVocabOutput2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KeyVocabOutput1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LevelB2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StructureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StructureOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VocabLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PersonALabel1)
                            .addComponent(PersonALabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LevelB2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StructureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StructureOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VocabLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeyVocabOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonALabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KeyVocabOutput2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonALabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KeyVocabOutput1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(back)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO
    }//GEN-LAST:event_backActionPerformed

    private void StructureOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StructureOutputActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_StructureOutputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane KeyVocabOutput;
    private javax.swing.JScrollPane KeyVocabOutput1;
    private javax.swing.JScrollPane KeyVocabOutput2;
    private javax.swing.JLabel LevelB2Label;
    private javax.swing.JLabel PersonALabel;
    private javax.swing.JLabel PersonALabel1;
    public static javax.swing.JTextArea PersonAOutput;
    public static javax.swing.JTextArea PersonBOutput;
    private javax.swing.JLabel StructureLabel;
    public static javax.swing.JTextField StructureOutput;
    private javax.swing.JLabel VocabLabel;
    public static javax.swing.JTextArea VocabOutput;
    private javax.swing.JButton back;
    // End of variables declaration//GEN-END:variables
    
 
   public void setPersonAOutput(String text) {
        PersonAOutput.setText(text);
    }
    

    
    public void setPersonBOutput(String text) {
        PersonBOutput.setText(text);
    }
    
    public void setVocabOutput(String text){
       VocabOutput.setText(text);
}
    
    public void setStructureOutput(String text){
        StructureOutput.setText(text);
    }
    
    
    
    
}    


