/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionListener;

/**
 *
 * @author W1771719 Seyed Avin Moosavi Shirazi, W1758597 Rabiul Alam, W1784229 Ibraheem Ahmed
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public void menu() {
        
    }
    
    public void addEventSignOut(ActionListener event) {
        cmdSignOut.addActionListener(event);
    }  
    public void addEventHelp(ActionListener event) {
        Help.addActionListener(event);
    }    
    public void addEventSettings(ActionListener event) {
        Settings.addActionListener(event);
    }
    public void addEventA1(ActionListener event) {
        A1.addActionListener(event);
    }
    public void addEventA2(ActionListener event) {
        A2.addActionListener(event);
    }
    public void addEventB1(ActionListener event) {
        B1.addActionListener(event);
    }
    public void addEventB2(ActionListener event) {
        B2.addActionListener(event);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLabel = new javax.swing.JLabel();
        Settings = new swing.MyButton();
        Help = new swing.MyButton();
        cmdSignOut = new swing.MyButton();
        Label1 = new javax.swing.JLabel();
        A1 = new swing.MyButton();
        B1 = new swing.MyButton();
        B2 = new swing.MyButton();
        A2 = new swing.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        MenuLabel.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(69, 68, 68));
        MenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLabel.setText("Menu");
        MenuLabel.setMaximumSize(new java.awt.Dimension(193, 59));
        MenuLabel.setMinimumSize(new java.awt.Dimension(193, 59));

        Settings.setBackground(new java.awt.Color(255, 153, 153));
        Settings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Settings.setForeground(new java.awt.Color(40, 40, 40));
        Settings.setText("Settings");
        Settings.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        Settings.setMaximumSize(new java.awt.Dimension(81, 27));
        Settings.setMinimumSize(new java.awt.Dimension(81, 27));
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        Help.setBackground(new java.awt.Color(255, 153, 153));
        Help.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Help.setForeground(new java.awt.Color(40, 40, 40));
        Help.setText("Help");
        Help.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        Help.setMaximumSize(new java.awt.Dimension(81, 27));
        Help.setMinimumSize(new java.awt.Dimension(81, 27));
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        cmdSignOut.setBackground(new java.awt.Color(255, 153, 153));
        cmdSignOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdSignOut.setForeground(new java.awt.Color(40, 40, 40));
        cmdSignOut.setText("Sign Out");
        cmdSignOut.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        cmdSignOut.setMaximumSize(new java.awt.Dimension(81, 27));
        cmdSignOut.setMinimumSize(new java.awt.Dimension(81, 27));
        cmdSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSignOutActionPerformed(evt);
            }
        });

        Label1.setForeground(new java.awt.Color(255, 153, 153));
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("Please select a language level");

        A1.setBackground(new java.awt.Color(255, 153, 153));
        A1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A1.setForeground(new java.awt.Color(40, 40, 40));
        A1.setText("A1\n");
        A1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        A1.setMaximumSize(new java.awt.Dimension(81, 27));
        A1.setMinimumSize(new java.awt.Dimension(81, 27));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 153, 153));
        B1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1.setForeground(new java.awt.Color(40, 40, 40));
        B1.setText("B1");
        B1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        B1.setMaximumSize(new java.awt.Dimension(81, 27));
        B1.setMinimumSize(new java.awt.Dimension(81, 27));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(255, 153, 153));
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.setForeground(new java.awt.Color(40, 40, 40));
        B2.setText("B2");
        B2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        B2.setMaximumSize(new java.awt.Dimension(81, 27));
        B2.setMinimumSize(new java.awt.Dimension(81, 27));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        A2.setBackground(new java.awt.Color(255, 153, 153));
        A2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        A2.setForeground(new java.awt.Color(40, 40, 40));
        A2.setText("A2");
        A2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        A2.setMaximumSize(new java.awt.Dimension(81, 27));
        A2.setMinimumSize(new java.awt.Dimension(81, 27));
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmdSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void cmdSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSignOutActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton A1;
    private swing.MyButton A2;
    private swing.MyButton B1;
    private swing.MyButton B2;
    private swing.MyButton Help;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel MenuLabel;
    private swing.MyButton Settings;
    private swing.MyButton cmdSignOut;
    // End of variables declaration//GEN-END:variables
}
