/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myownprivateone;

/**
 *
 * @author Ibraheem
 */
public class Context_B1 extends javax.swing.JPanel {

    /**
     * Creates new form Context_A3
     */
    public Context_B1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        B1_Cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        B1_Sub_Cmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 68, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Level B1");

        backBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(30, 122, 236));
        backBtn.setText("Back");
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        B1_Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "University life", "Making travel arrangements", "Going shopping and asking for prices", "Socialising in the country", "Weather", "Ordering food and drink", "Making invitations", "Housing conditions" }));
        B1_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_CmbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Context:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Sub-Context:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(B1_Sub_Cmb, 0, 236, Short.MAX_VALUE)
                            .addComponent(B1_Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B1_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B1_Sub_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void B1_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_CmbActionPerformed
        if(B1_Cmb.getSelectedItem().equals("University life")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Study plans");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Making travel arrangements")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("E-Ticket");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Going shopping and asking for prices")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("E-Ticket");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Socialising in the country")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Purchase of computer");
            B1_Sub_Cmb.addItem("Cancel hair appointment");
            B1_Sub_Cmb.addItem("Payment");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Weather")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Rain in station");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Ordering food and drink")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Ordering cocktails by barcode");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Making invitation")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Offering help for Pink Unicorn Party");
        }
        else
        if(B1_Cmb.getSelectedItem().equals("Housing conditions")){
            B1_Sub_Cmb.removeAllItems();
            B1_Sub_Cmb.setSelectedItem(null);
            B1_Sub_Cmb.addItem("Delivery of packages");
        }
    }//GEN-LAST:event_B1_CmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> B1_Cmb;
    private javax.swing.JComboBox<String> B1_Sub_Cmb;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
