/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myownprivateone;

/**
 *
 * @author Ibraheem
 */
public class Context_A2 extends javax.swing.JPanel {

    /**
     * Creates new form Context_A10
     */
    public Context_A2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderingBtn = new swing.MyButton();
        ExchangingBtn = new swing.MyButton();
        AppointmentBtn = new swing.MyButton();
        ShoppingBtn = new swing.MyButton();
        IntroductionBtn = new swing.MyButton();
        HealthBtn = new swing.MyButton();
        InvitationBtn = new swing.MyButton();
        SocialisingBtn = new swing.MyButton();
        DirectionBtn = new swing.MyButton();
        TravelBtn = new swing.MyButton();
        CulturalBtn = new swing.MyButton();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new swing.MyButton();
        WeatherBtn = new swing.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        OrderingBtn.setBackground(new java.awt.Color(125, 229, 251));
        OrderingBtn.setForeground(new java.awt.Color(40, 40, 40));
        OrderingBtn.setText("Ordering food and drink");

        ExchangingBtn.setBackground(new java.awt.Color(125, 229, 251));
        ExchangingBtn.setForeground(new java.awt.Color(40, 40, 40));
        ExchangingBtn.setText("Exchanging personal information");

        AppointmentBtn.setBackground(new java.awt.Color(125, 229, 251));
        AppointmentBtn.setForeground(new java.awt.Color(40, 40, 40));
        AppointmentBtn.setText("Making appointments");

        ShoppingBtn.setBackground(new java.awt.Color(125, 229, 251));
        ShoppingBtn.setForeground(new java.awt.Color(40, 40, 40));
        ShoppingBtn.setText("Going shopping and asking for prices");

        IntroductionBtn.setBackground(new java.awt.Color(125, 229, 251));
        IntroductionBtn.setForeground(new java.awt.Color(40, 40, 40));
        IntroductionBtn.setText("Introductions");

        HealthBtn.setBackground(new java.awt.Color(125, 229, 251));
        HealthBtn.setForeground(new java.awt.Color(40, 40, 40));
        HealthBtn.setText("Health matters");

        InvitationBtn.setBackground(new java.awt.Color(125, 229, 251));
        InvitationBtn.setForeground(new java.awt.Color(40, 40, 40));
        InvitationBtn.setText("Making invitations");

        SocialisingBtn.setBackground(new java.awt.Color(125, 229, 251));
        SocialisingBtn.setForeground(new java.awt.Color(40, 40, 40));
        SocialisingBtn.setText("Socialising in the country");

        DirectionBtn.setBackground(new java.awt.Color(125, 229, 251));
        DirectionBtn.setForeground(new java.awt.Color(40, 40, 40));
        DirectionBtn.setText("Asking and giving directions");

        TravelBtn.setBackground(new java.awt.Color(125, 229, 251));
        TravelBtn.setForeground(new java.awt.Color(40, 40, 40));
        TravelBtn.setText("Making travel arrangements");

        CulturalBtn.setBackground(new java.awt.Color(125, 229, 251));
        CulturalBtn.setForeground(new java.awt.Color(40, 40, 40));
        CulturalBtn.setText("Cross-cultural experiences");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 68, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Context");

        backBtn.setForeground(new java.awt.Color(40, 40, 40));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        WeatherBtn.setBackground(new java.awt.Color(125, 229, 251));
        WeatherBtn.setForeground(new java.awt.Color(40, 40, 40));
        WeatherBtn.setText("Weather");
        WeatherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeatherBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Level A2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DirectionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CulturalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TravelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SocialisingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvitationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShoppingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HealthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExchangingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(IntroductionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WeatherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(IntroductionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DirectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InvitationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ShoppingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HealthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SocialisingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TravelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExchangingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CulturalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WeatherBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void WeatherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeatherBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeatherBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton AppointmentBtn;
    private swing.MyButton CulturalBtn;
    private swing.MyButton DirectionBtn;
    private swing.MyButton ExchangingBtn;
    private swing.MyButton HealthBtn;
    private swing.MyButton IntroductionBtn;
    private swing.MyButton InvitationBtn;
    private swing.MyButton OrderingBtn;
    private swing.MyButton ShoppingBtn;
    private swing.MyButton SocialisingBtn;
    private swing.MyButton TravelBtn;
    private swing.MyButton WeatherBtn;
    private swing.MyButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
