/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.myownprivateone;

/**
 *
 * @author Ibraheem
 */
public class Context_A2 extends javax.swing.JPanel {

    /**
     * Creates new form Context_A10
     */
    public Context_A2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backBtn = new swing.MyButton();
        A2_Cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        A2_Sub_Cmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 68, 68));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Level A2");

        backBtn.setForeground(new java.awt.Color(40, 40, 40));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        A2_Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Introductions", "Making appointments", "Asking and giving directions", "Making invitations", "Ordering food and drink", "Going shopping and asking for prices", "Health matters", "Socialising in the country", "Making travel arrangements", "Exchanging personal information", "Cross-cultural experieneces", "Weather" }));
        A2_Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_CmbActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Context:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Sub-Context:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(A2_Sub_Cmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(A2_Cmb, javax.swing.GroupLayout.Alignment.LEADING, 0, 236, Short.MAX_VALUE))
                        .addGap(0, 50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A2_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A2_Sub_Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void A2_CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_CmbActionPerformed
        if(A2_Cmb.getSelectedItem().equals("Introductions")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("1st dat in job");
            A2_Sub_Cmb.addItem("Job offer");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making appointments")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Dentist");
            A2_Sub_Cmb.addItem("Doctor");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Asking and giving directions")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Delivery Driver");
            A2_Sub_Cmb.addItem("Hospital Visit");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making invitations")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Charity");
            A2_Sub_Cmb.addItem("Lunch");
            A2_Sub_Cmb.addItem("Children at wedding");
            A2_Sub_Cmb.addItem("Lunch");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Ordering food and drink")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Vegan pizza");
            A2_Sub_Cmb.addItem("Reservation");
            A2_Sub_Cmb.addItem("Delayed drinks order");
            A2_Sub_Cmb.addItem("QR Code");
            A2_Sub_Cmb.addItem("Cocktails (1)");
            A2_Sub_Cmb.addItem("Cocktails (2)");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Going shopping and asking for prices")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Payment");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Health matters")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Visiting patient");
            A2_Sub_Cmb.addItem("Sick relative");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Socialising in the country")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Succulent");
            A2_Sub_Cmb.addItem("Family size");
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Making travel arrangements")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Expired tickets");   
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Exchanging personal information")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Age restricted");  
        }
        else
        if(A2_Cmb.getSelectedItem().equals("Cross-cultural experieneces")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Omelette");  
        }     
        else
        if(A2_Cmb.getSelectedItem().equals("Weather")){
            A2_Sub_Cmb.removeAllItems();
            A2_Sub_Cmb.setSelectedItem(null);
            A2_Sub_Cmb.addItem("Clothing for weather");  
        }    
    }//GEN-LAST:event_A2_CmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A2_Cmb;
    private javax.swing.JComboBox<String> A2_Sub_Cmb;
    private swing.MyButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
